[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.devnet]
quresis = "7SwY7dD2rQTvWs8KUB1xsy3GuUbKBoJdcPvx8kGiuojv"
quresis_hook = "9P6cDkGwt3AADtVtFLy3nCHz3ZDLnMLpscUmVFqosvB4"

[programs.localnet]
quresis = "4RcF26R7sj9tbvPPA2m4oVbueAYSbX8XUBKMhybEVxis"
quresis_hook = "HookQR5iS1E8j7q5xGvB6Ux7tfPQCzrS5C3nH8K4z2M7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
shutdown_wait = 5000
upgradeable = false
