[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.devnet]
quresis = "7SwY7dD2rQTvWs8KUB1xsy3GuUbKBoJdcPvx8kGiuojv"
quresis_hook = "9P6cDkGwt3AADtVtFLy3nCHz3ZDLnMLpscUmVFqosvB4"

[programs.localnet]
quresis = "7SwY7dD2rQTvWs8KUB1xsy3GuUbKBoJdcPvx8kGiuojv"
quresis_hook = "9P6cDkGwt3AADtVtFLy3nCHz3ZDLnMLpscUmVFqosvB4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
demo = "yarn run ts-node scripts/demo.ts"
video = "yarn run ts-node scripts/video-demo.ts"

[test]
startup_wait = 30000
shutdown_wait = 5000
upgradeable = false
